### ISSUE TITLE
Consecutive calculations output incorrect results

### ISSUE THREAD

**Issue by anon-pr** [skywarth/country-routing-algorithm#2]
Consecutive calculations through the UI provide incoherent results. Told ya that one day global vars gonna bite you on the bottom.

Big L

**Comment by skywarth** [comment]
Ah sh#t, here we go again.

Problem most probably originates from keeping `distanceBetweenNode` and `distanceToFinalDestination`. keeping `distanceBetweenNode` should be alright but `distanceToFinalDestination` is the source of evil.

I'll be back...

**Comment by skywarth** [comment]
You want some more, Mr Toad ?
